# Config file for automatic testing at travis-ci.org
services: mongodb
language: python
python:
  - 3.6
  - cp tweego/config_example tweego.config


# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt 
  - pip install -r requirements_dev.txt
         
# Command to run tests, e.g. python setup.py test
script: 
  - pylint tweego/
  - python -m pytest

